sudo: required

language: node_js

node_js:
- '5'

deploy:
  provider: npm
  on:
    tags: true
    branch: master
  api_key:
    secure: 1ZEBvKG4oMipy+7VwZZ7WLpkZH+0euIFI5RztUqZ9o64rblXz7i5QJU4ipHUM7OhPhpPodP2iAeVSkSakt1KXljj2UcvHLm3PoAXXUahOMajxoMoNusRubMaaakYFw1OkAVsUqGWo+K2abBqgdFgnwf2G1epygrCp+B0fEiSdfnqWpUpf3/Izar0zClUQrEDUfJbLP6rICiVx269i1WRkQxQ8Q1FBtjXW0WG3OZBUy6xwZjT6JvmCoLxT+XLxNoMrTTm6sIgREV2rnrdmlQisKRhSh7SzxDaHKtLiP1ICgWoIlKFrBiCl38i5UtxhfLBm0xyD/lrsb3NmOPNBwekLV3FMXkS9Cb00/Xs9S/R2QNikvkJPW/itryNJF8GHU/L65UOA2x/CFYWIrWS2IZVA9Pu8q7e9rnVTMMMyCbXA0jPxwUgiib8GuXc15lTNKiV/90C9RRK1IW3jI/2ab93DMqrMzR0n3Syo8702LY7pIjFNCnvIa4gkOIpfI/+4gjmmKPIcOEEtCnlE6hUsDpwzmSgG2MbMYvhP+aEsKoG586CBwJHgp9l6reQThbarlacDoHy5VdhlSkpeRiZ3F9Sbe/TUFuvzF3g6Q1DXPZKP5OzUIV2y8CMVJ5sGy18LOGT+mPFCpWXmkHaJbKs0pJZ/uiKsVMoUBIbF6M3oxZ+Fqw=

notifications:
  slack:
    secure: mve8/fpNKt7uzBX/aeoXB09tEJVY9RkbudAyw6hZf6OttXwjwh78WZ2ZeUKKfdAXIq7BsssgQBK9C9w7bB0SPFjyex2O8aeFjeJvpnTRJ8ntvuZWvIBQY0BEw00zl53g/d7EdnRwA3y6AyZRoEdjm2NAKW65D2tFISCz/p3qZ1hyf03VpRw8AOAZd7unu9fVl1fw/pHypIiEXWkmkFazH10UY8knvF4A1e1QWxLD7W3qYnwXsYf62GMZCOWN5vdlygWNvR3GvrqhglPJuG8nFI9ZBoalHgmRFUtgll1S2eOFKgGizfOWCGMIHWV2itHRBiQQrzzh5j9qxKaUN8zESymlI/rsA+mODGsw4cab0mwDPzvTu9XoAr/2geIThd2258hrLH0Z4esQm0apzpw2IytlgiAweBAnDdGeye7H2D4uJiaDbKDhEROadunCRSC5SlCm7wsS900H94HEfN/QLBvoMcD3pZXPXOMM4s1afaEXWeUwCZWZWHuzzIBNZ2UVARdKChax+uz7UvsLAuyuR1byTDraIqtTcfL4o+3tTbZM9jOas3X8RYobYfJrClRGizz5OylCQK/3o8+c8dPqtTFKce87COutDktVdWXMEW4UyXCANVpWvBBalrIURMRy4h17i3qxUGC8OhY/W1NWd/M+pVezmjjJTtzBVSphuXA=
